<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.translation_debug' shared service.

$this->privates['console.command.translation_debug'] = $instance = new \Symfony\Bundle\FrameworkBundle\Command\TranslationDebugCommand(($this->services['translator'] ?? $this->getTranslatorService()), ($this->privates['translation.reader'] ?? $this->load('getTranslation_ReaderService.php')), ($this->privates['translation.extractor'] ?? $this->load('getTranslation_ExtractorService.php')), '/code/translations', '/code/templates', [0 => '/code/vendor/symfony/validator/Resources/translations', 1 => '/code/vendor/symfony/form/Resources/translations', 2 => '/code/vendor/symfony/security-core/Resources/translations', 3 => '/code/translations'], [0 => '/code/templates', 1 => '/code/vendor/symfony/twig-bridge/Resources/views/Form', 2 => '/code/vendor/symfony/framework-bundle/Command/TranslationDebugCommand.php', 3 => '/code/vendor/symfony/form/Extension/Core/Type/FileType.php', 4 => '/code/vendor/symfony/form/Extension/Core/Type/TransformationFailureExtension.php', 5 => '/code/vendor/symfony/form/Extension/Validator/Type/UploadValidatorExtension.php', 6 => '/code/vendor/symfony/form/Extension/Csrf/Type/FormTypeCsrfExtension.php', 7 => '/code/vendor/symfony/validator/Util/LegacyTranslatorProxy.php', 8 => '/code/vendor/symfony/framework-bundle/CacheWarmer/TranslationsCacheWarmer.php', 9 => '/code/vendor/symfony/translation/DataCollector/TranslationDataCollector.php', 10 => '/code/vendor/symfony/twig-bridge/Extension/TranslationExtension.php']);

$instance->setName('debug:translation');

return $instance;
