<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.translation_update' shared service.

$a = new \Symfony\Component\Translation\Writer\TranslationWriter();
$a->addDumper('php', new \Symfony\Component\Translation\Dumper\PhpFileDumper());
$a->addDumper('xlf', new \Symfony\Component\Translation\Dumper\XliffFileDumper());
$a->addDumper('po', new \Symfony\Component\Translation\Dumper\PoFileDumper());
$a->addDumper('mo', new \Symfony\Component\Translation\Dumper\MoFileDumper());
$a->addDumper('yml', new \Symfony\Component\Translation\Dumper\YamlFileDumper());
$a->addDumper('yaml', new \Symfony\Component\Translation\Dumper\YamlFileDumper('yaml'));
$a->addDumper('ts', new \Symfony\Component\Translation\Dumper\QtFileDumper());
$a->addDumper('csv', new \Symfony\Component\Translation\Dumper\CsvFileDumper());
$a->addDumper('ini', new \Symfony\Component\Translation\Dumper\IniFileDumper());
$a->addDumper('json', new \Symfony\Component\Translation\Dumper\JsonFileDumper());
$a->addDumper('res', new \Symfony\Component\Translation\Dumper\IcuResFileDumper());

$this->privates['console.command.translation_update'] = $instance = new \Symfony\Bundle\FrameworkBundle\Command\TranslationUpdateCommand($a, ($this->privates['translation.reader'] ?? $this->load('getTranslation_ReaderService.php')), ($this->privates['translation.extractor'] ?? $this->load('getTranslation_ExtractorService.php')), 'en', '/code/translations', '/code/templates', [0 => '/code/vendor/symfony/validator/Resources/translations', 1 => '/code/vendor/symfony/form/Resources/translations', 2 => '/code/vendor/symfony/security-core/Resources/translations', 3 => '/code/translations'], [0 => '/code/templates', 1 => '/code/vendor/symfony/twig-bridge/Resources/views/Form', 2 => '/code/vendor/symfony/framework-bundle/Command/TranslationDebugCommand.php', 3 => '/code/vendor/symfony/form/Extension/Core/Type/FileType.php', 4 => '/code/vendor/symfony/form/Extension/Core/Type/TransformationFailureExtension.php', 5 => '/code/vendor/symfony/form/Extension/Validator/Type/UploadValidatorExtension.php', 6 => '/code/vendor/symfony/form/Extension/Csrf/Type/FormTypeCsrfExtension.php', 7 => '/code/vendor/symfony/validator/Util/LegacyTranslatorProxy.php', 8 => '/code/vendor/symfony/framework-bundle/CacheWarmer/TranslationsCacheWarmer.php', 9 => '/code/vendor/symfony/translation/DataCollector/TranslationDataCollector.php', 10 => '/code/vendor/symfony/twig-bridge/Extension/TranslationExtension.php']);

$instance->setName('translation:update');

return $instance;
