<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_oauth_server.authorize.form' shared service.

return ($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php'))->createNamed('fos_oauth_server_authorize_form', 'FOS\\OAuthServerBundle\\Form\\Type\\AuthorizeFormType', NULL, ['validation_groups' => $this->parameters['fos_oauth_server.authorize.form.validation_groups']]);
