<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\MeetVonq\Http\Controller\HomeController' shared autowired service.

return $this->services['App\\MeetVonq\\Http\\Controller\\HomeController'] = new \App\MeetVonq\Http\Controller\HomeController();
