<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.App\MeetVonq\Console\ProjectTestCommand' shared autowired service.

return $this->services['console.command.public_alias.App\\MeetVonq\\Console\\ProjectTestCommand'] = new \App\MeetVonq\Console\ProjectTestCommand();
