<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'project.fractal.manager' shared service.

include_once $this->targetDirs[3].'/vendor/league/fractal/src/Manager.php';
include_once $this->targetDirs[3].'/src/MeetVonq/App/Support/FractalService.php';

return $this->services['project.fractal.manager'] = new \App\MeetVonq\App\Support\FractalService('http://127.0.0.1:9002/api');
