users.create:
    path: "/api/user/create"
    methods: POST
    controller: App\MeetVonq\Http\Controller\UserController:create

users.get:
    path: "/api/users"
    methods: GET
    controller: App\MeetVonq\Http\Controller\UserController:index

users.get.by.id:
    path: "/api/user/{id}"
    methods: GET
    controller: App\MeetVonq\Http\Controller\UserController:user

groups.get:
    path: "/api/group/{id}"
    methods: GET
    controller: App\MeetVonq\Http\Controller\GroupController:get
