<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6GypbKN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6GypbKN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6GypbKN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6GypbKN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6GypbKN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6GypbKN',
    'container.build_id' => 'df1e7b09',
    'container.build_time' => 1563227677,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6GypbKN');
