<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/api/doc']], [], []],
    'fos_oauth_server_token' => [[], ['_controller' => 'fos_oauth_server.controller.token:tokenAction'], [], [['text', '/oauth/v2/token']], [], []],
    'fos_oauth_server_authorize' => [[], ['_controller' => 'fos_oauth_server.controller.authorize:authorizeAction'], [], [['text', '/oauth/v2/auth']], [], []],
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception::showAction'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception::cssAction'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'nelmio_api_doc.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/']], [], []],
    'users.get' => [[], ['_controller' => 'App\\MeetVonq\\Http\\Controller\\UserController:index'], [], [['text', '/api/users']], [], []],
    'users.get.by.id' => [['id'], ['_controller' => 'App\\MeetVonq\\Http\\Controller\\UserController:user'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/api/user']], [], []],
    'app_authorization_oauthauthorize_authorize' => [[], ['_controller' => 'App\\Authorization\\Controller\\OAuthAuthorizeController::authorize'], [], [['text', '/oauth/v2/auth']], [], []],
    'app_authorization_oauthtoken_token' => [[], ['_controller' => 'App\\Authorization\\Controller\\OAuthTokenController::tokenAction'], [], [['text', '/oauth/v2/token']], [], []],
];
