<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'a53b8291f3439dcbb124b496d3c889c0',
  'DATABASE_DRIVER' => 'pdo_mysql',
  'DATABASE_SERVER_VERSION' => '5.7',
  'DATABASE_URL' => 'mysql://root:root@localDb:3306/vonq',
);
